theme: minima
title: Sergio's Blog!
author: Sergio Luis Ayala
email: serg5l@domain.com
description: > # this means to ignore newlines until "baseurl:"
  First GitHub page :)

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
